"""nullable address_id

Revision ID: 375f2e24c5a6
Revises: 22979b1c4692
Create Date: 2025-11-18 10:19:20.772857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375f2e24c5a6'
down_revision: Union[str, Sequence[str], None] = '22979b1c4692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
