"""add order_products table

Revision ID: 4bfd37b41d80
Revises: 14992d0ffd59
Create Date: 2025-11-17 22:03:43.654300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfd37b41d80'
down_revision: Union[str, Sequence[str], None] = '14992d0ffd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_product_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_product_id_fkey'), 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
