"""add order_products table

Revision ID: 9c5bd1c0ee27
Revises: 4bfd37b41d80
Create Date: 2025-11-17 22:16:29.156871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5bd1c0ee27'
down_revision: Union[str, Sequence[str], None] = '4bfd37b41d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
